spring.application.name=kafka-query-engine-operator
k8s.namespace=kafka

server.port=8081

# KQE API configuration
kqe.api.base-path=
kqe.api.query-path=/query
kqe.api.messages-path=/messages
kqe.api.index-status-path=/index/status
kqe.api.index-path=/index
